import './globals.css';
import type { Metadata } from 'next';
import { MenuItems } from '@/components/menu-items';
import { ThemeButton } from '@/components/theme-button';
import Providers from './provider';
export const metadata: Metadata = {
  title: 'Berker Kelesoglu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeButton />
          <div className="flex justify-between">
            <div className="lg:flex md:hidden sm:hidden min-h-screen">
              <div className="w-1/4 relative">
                <MenuItems />
              </div>
            </div>
            <div className="flex justify-center items-center">
              <div className="w-3/4 min-h-screen p-10">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
